In [2]:
import numpy as np
a=np.array([1,2,3])
print("One dimensional array a=",a)
b=np.array([[1,2,3],[4,5,6]])
print("Two dimensionaal array b=",b)
print("Size of array",a.shape)
print("Element at indices 0,1,2:",a[0],a[1],a[2])
a[0]=5
print("Array after changing the element at index 0:",a)
a=np.zeros((2,2))
print("array of all zeroes",a)
b=np.ones((1,2))
print("Array of all ones",b)
c=np.full((2,2),7)
print("An constant array",c)
d=np.eye(2)
print("A 2*2 identity matrix",d)
e=np.random.random((1,2))
print("An array with random values",e)



One dimensional array a= [1 2 3]
Two dimensionaal array b= [[1 2 3]
 [4 5 6]]
Size of array (3,)
Element at indices 0,1,2: 1 2 3
Array after changing the element at index 0: [5 2 3]
array of all zeroes [[0. 0.]
 [0. 0.]]
Array of all ones [[1. 1.]]
An constant array [[7 7]
 [7 7]]
A 2*2 identity matrix [[1. 0.]
 [0. 1.]]
An array with random values [[0.88132792 0.29454914]]


In [18]:
import numpy as np
print("Array indexing:slicing")
a1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("a1=",a1)
b=a1[:2,1:3]
print("subarray consisting of first two rows and columns 1 and 2:",b)
b=a1[1:2,:]
print("subarray consisting of second row",b)
print("Accessing columns:")
b=a1[:,1]
print(b,b.shape)
c=a1[:,1:2]
print(c,c.shape)
print("Array integer indexing:")
a2=np.array([[1,2],[3,4],[5,6]])
print("a2=",a2)
print("Example of array integer indexing:",a2[[0,1,2],[0,1,0]])
print(a2[[0,0],[1,1]])
print(np.array([a2[0,1],a[0,1]]))
a3=a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a3=",a3)
b=np.array([0,2,0,1])
print("b=",b)
print("a3=",a3[np.arange(4),b])
a3[np.arange(4),b]+=10
print("a3=",a3)
print("boolean array indexing")
a=np.array([[1,2],[3,4],[5,6]])
print("a=",a)
bool_idx=(a>2)
print("Elements greater than 2",a[bool_idx])

Array indexing:slicing
a1= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
subarray consisting of first two rows and columns 1 and 2: [[2 3]
 [6 7]]
subarray consisting of second row [[5 6 7 8]]
Accessing columns:
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
Array integer indexing:
a2= [[1 2]
 [3 4]
 [5 6]]
Example of array integer indexing: [1 4 5]
[2 2]
[2 2]
a3= [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b= [0 2 0 1]
a3= [ 1  6  7 11]
a3= [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
boolean array indexing
a= [[1 2]
 [3 4]
 [5 6]]
Elements greater than 2 [3 4 5 6]


In [24]:
import numpy as np
x = np.array([[1,2], [3, 4]], dtype=np.float64) 
y = np.array([[6,9], [4, 4]], dtype=np.float64)

print("x = ",x)

print("y =",y)

print("Element wise addition: ",np.add(x, x))

print("Element wise subtraction: ",np.subtract(x, y))

print("Element wise multiplication: ",np.multiply(x, y))

print("Element wise square root of x: ",np.sqrt(x))

print("Matrix multiplication: ",np.dot(x, y))

print("Sum of all elements of matrix x: ",np.sum(x))

print("Sum of elements in each column of matrix y: ",np.sum(y,axis=0))

print("Sum of elements in each row of matrix y: ",np.sum(y,axis=1))

print("Transpose of matrix x: ",x.T)


x =  [[1. 2.]
 [3. 4.]]
y = [[6. 9.]
 [4. 4.]]
Element wise addition:  [[2. 4.]
 [6. 8.]]
Element wise subtraction:  [[-5. -7.]
 [-1.  0.]]
Element wise multiplication:  [[ 6. 18.]
 [12. 16.]]
Element wise square root of x:  [[1.         1.41421356]
 [1.73205081 2.        ]]
Matrix multiplication:  [[14. 17.]
 [34. 43.]]
Sum of all elements of matrix x:  10.0
Sum of elements in each column of matrix y:  [10. 13.]
Sum of elements in each row of matrix y:  [15.  8.]
Transpose of matrix x:  [[1. 3.]
 [2. 4.]]


In [26]:
import numpy as np

print("Example for broadcasting: ")

v=np.array([1,2,3])

w=np.array([4,5])

print("v = ",v)

print("w = ",w)

print("Outer product of above vectors: ")

print(np.reshape(v,(3,1))*w)

x=np.array([[1,2,3],[4,5,6]])

print("x = ",x)

print("Resultant matrix after adding the vector x to each row of matrix v: ") 
print(x+v)

print("Example for broadcasting fails: ")

print("Adding the vector x to each column of matrix w will generate an error")

print("Solution: Reshape the matrix w then the result will be: ")

print(x+np.reshape(w, (2,1)))

Example for broadcasting: 
v =  [1 2 3]
w =  [4 5]
Outer product of above vectors: 
[[ 4  5]
 [ 8 10]
 [12 15]]
x =  [[1 2 3]
 [4 5 6]]
Resultant matrix after adding the vector x to each row of matrix v: 
[[2 4 6]
 [5 7 9]]
Example for broadcasting fails: 
Adding the vector x to each column of matrix w will generate an error
Solution: Reshape the matrix w then the result will be: 
[[ 5  6  7]
 [ 9 10 11]]
